version: '3'

services:
  php:
    build:
      context: .
    volumes:
      - ./:/var/www/blog

  web:
    image: nginx:1.17
    working_dir: /var/www/blog
    volumes:
      - ./:/var/www/blog
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "1945:80"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ~/data/db/mysql/blog:/var/lib/mysql
    ports:
      - "3311:3306"
